### ISSUE TITLE
MBTA app is not showing blue line trains for Orient Heights station

### ISSUE THREAD

**Issue by ganyr1017** [tidbyt/community#1218] opened 2023-03-15 16:55 UTC
@marcusb Trying to use the MBTA schedule app and saw Orient Heights does not show the Blue line train arrivals 
![image](https://user-images.githubusercontent.com/123271346/225382473-ae7889da-3d86-4a9f-ad97-bc36569ded94.png)

**Comment by ganyr1017** [comment] 2023-03-15 20:51
Did realize tese are also bus lines into winthrop, Would be nice to be able to select what I want to track if a station/stop has multiple option (seems to be the issue here since Orient heights has multiple bus lines plus the blue line)

**Comment by marcusb** [comment] 2023-03-19 21:32
Thanks for reporting. The issue is that the station has multiple "child stations", and the Blue Line is only connected to one of the substations. This should be fixable.

**Comment by marcusb** [comment] 2023-03-19 21:56
That wasn't it at all, it was an artifact of the sorting params. That should be fixed by the above PR, so the Blue Line shows up when it has the nearest departures.

But the underlying problem is that there are several routes on that stop, and we can only fit two, so now you can the opposite problem, eg only showing the two Blue Lines in each direction and not showing any buses. The current approach isn't very scalable, but I'm not sure what the best option is given pixlet's UI limitations.

**Closed** 2023-04-20 10:13 UTC
Labels: wontfix
