### ISSUE TITLE
Weather Alerts Jumbled

### ISSUE THREAD

**Issue by btjones** [tidbyt/community#646] opened 2022-09-09 00:34 UTC
@aschechter88 I received my first alert and for a few seconds each time it loads it’s a bit funky and jumbled before fixing itself.

![image](https://user-images.githubusercontent.com/155808/189248611-b700612f-6b3e-4f3b-bfb7-39bb39e58b5d.jpeg)

**Comment by btjones** [comment] 2022-09-09 01:47
If it helps, here are a couple more screenshots someone else posted on discord.

![image](https://user-images.githubusercontent.com/155808/189254973-d453b688-e971-49de-87c4-e710bc00a350.jpeg)

![image](https://user-images.githubusercontent.com/155808/189254986-ab263f71-17a3-4a18-b80e-efb1f3ff7f2b.jpeg)

**Comment by rs7q5** [comment] 2022-09-09 03:12
Could it somehow be due to cached data or keys or something? I've had that happen when weird stuff like this happens.

**Comment by rs7q5** [comment] 2022-10-02 05:03
@aschechter88 any timeline for an update on this. I know it's been mentioned on the discourse too. 

And I know people would like an option to have it not in the rotation unless there are alerts too, which I could add but wanted to check if you had something int he works first for the bigger issue.

**Comment by rs7q5** [comment] 2022-10-03 18:48
You just have to do `return []` and it won't show up in the rotation. So the easiest solution may be to have a toggle that if there are no alerts then just do `return []` instead of `return render.Root()`.

I think when I looked at the code the first time I couldn't find a good place to add it as I wasn't sure how you were filling the text and everything. 

I am wondering if you have a cache issue or something so that is why you aren't able to reproduce locally, you may have to hard code to recreate or maybe find a place with alerts and see if you can get it to show up in `pixlet serve`. I don't know what your cache keys are though either or what is being cached. I'm just throwing stuff out of things to check.

**Comment by rs7q5** [comment] 2022-10-06 23:52
@aschechter88  I am 99% sure the issue may be that you need to use `render.Animation` and not `render.Sequence` I think you need to use modules from the animation widget instead for that to work properly. @fxb is `render.Sequence` built exclusively with the idea of using it with the functions from the animation module (i.e. what is a use case to use this over `render.Animation` if not using `animation` commands?)

I have not play tested it more than swapping one of my apps from `render.Animation` to `render.Sequence` and I seem to get similar overlapping results as your jumbled cards when using `render.Sequence`

did not change in my PR for your app as I wanted you to play around with display timings and what not.

**Comment by rs7q5** [comment] 2022-10-07 14:12
For what it's worth I also have the overlapping text thing today.

**Comment by rs7q5** [comment] 2022-10-07 16:35
1. This is not my location, but looks like any place in the upper midwest should give you a frost advisory warning. (checked weather.gov)
2. A noticing the `render.Animation` and `render.Sequence` thing last night, I really don't think your cache stuff is the issue either because you are doing it by truncated latitude and longitude and saving the data and not the frames based on the code. Additionally  I tried swapping one of my apps that was using `render.Animation` with `render.Sequence` and I got the same jumbled issue. The slides aren't actually jumbled per se, I think they're just stacking and overlapping and your delay is so long that it doesn't dissappear quick enough, either way without using `animation.Transformation` in your stuff I think the way you need to go is with `render.Animation` to get a pagination since I'm guessing that's what you want.

So, if you simply swap that from `render.Sequence` to `render.Animation` in the line below they should no longer be overlapping. You may have to play with delay though. 

https://github.com/tidbyt/community/blob/778322bd3d6949c755040aa2fa9c07ebb913d7ed/apps/severewxalertsusa/severewxalertsusa.star#L56

**Comment by rs7q5** [comment] 2022-10-07 16:45
Yeah I think the `render.Animation` patch may be a good intermediate fix if you want the changes to be fancy rather than just paginate, but the app isn't super useful with this bug. 

Also it looks like on my tidbyt app, the `render.Sequence` does work as I saw it on my other app, but again, you need to put a background behind the text (could be solved with `render.Box), but I think the easiest solution is just changing to `render.Animation`.

Thanks for fixing it! It also looks like the toggle for alerts only also got merged, so that should be useable on your end if you have no alerts in your current area.

**Comment by rs7q5** [comment] 2022-10-07 16:49
Also feel free to change the toggle icon on the alert only, I used `eyeSlash` as I usually use it to hide app, but another font-awesome icon may make more sense. Potentially `circleExclamation` `exclamation` or `triangleExclamation` as I made it eyeSlash since I was thinking of hide app, not alerts only. But I do think `eyeSlash` may be more differentiable in case you add extra settings to this app and maybe only want to see certain types of alerts.

**Comment by rs7q5** [comment] 2022-10-07 19:48
@aschechter88  I was able to test the switch out, you'll need to play with the transition, but here's me just running pixlet render. Before then after. as I said you will need to change the delay, as it seems a little long.

Before:
![severewxalertsusa](https://user-images.githubusercontent.com/46969733/194641933-2ac28bc8-c9b3-46a7-962c-71380b02165a.gif)

After:
![severewxalertsusa](https://user-images.githubusercontent.com/46969733/194642040-8a733374-5b27-4d56-a28d-ddd9eb769520.gif)

**Closed** 2022-10-20 16:14 UTC
